federation_version: 2
subgraphs:
  users:
    routing_url: http://localhost:4070/
    schema:
      subgraph_url: http://localhost:4070/
  reviews:
    routing_url: http://localhost:4090/
    schema:
      subgraph_url: http://localhost:4090/
  products:
    routing_url: http://localhost:4080/
    schema:
      subgraph_url: http://localhost:4080/
